### ISSUE TITLE
Could you explain concept of offset

### ISSUE THREAD

**Issue by hackerzone85** [carlosproca/cdnormbio#1]
I do not understand these two commands i.e. concept of adding offset.
Could you explain? Please..
```
offset.added <- rnorm( sample.n )
expr.data <- sweep( expr.data, 2, offset.added, "+" )
```

**Comment by carlosproca** [comment]
Hi Mahendra, 
`offset.added` simulates what would be the technical variation that needs to be detected and removed from the data. It is just a number for each sample, that is, for each column of the matrix `expr.data`. The `sweep()` call adds those numbers, by columns, to `expr.data`
