### ISSUE TITLE
normalize.svcd: There must be 2 or more samples for each condition

### ISSUE THREAD

**Issue by hackerzone85** [carlosproca/cdnormbio#2]
I have expression data of 3 sample. When i ran this command, i got following error.
Is replicates of sample is compulsory to run this command?
```
normalize.result <- normalize.svcd(expr.data, expr.condition,  stdvec.graph = "stdvec", p.value.graph = "p_value",  verbose = TRUE)
Error in normalize.svcd(expr.data, expr.condition, stdvec.graph = "stdvec",  : 
normalize.svcd: There must be 2 or more samples for each condition
```
[expr.data.xlsx](https://github.com/carlosproca/cdnormbio/files/840727/expr.data.xlsx)

**Comment by carlosproca** [comment]
Hi Mahendra, 
This method needs at least **two** samples per experimental condition. But it can handle three samples of the same experimental condition. 
If your three samples correspond to the same experimental condition, you just have to indicate so with the vector `expr.condition`, following the same format as in the examples.
